### PR TITLE
Don't just unwrap() on references to non-local tables

### LINKED ISSUE #250: [lucetc] thread 'main' panicked at lucetc::decls::ModuleDecls::get_table
### Environment

| Questions            | Answers
|----------------------|--------------------
| Related Binary       | lucetc
| Commit               | commit 2c2b035415703499c8d1e03ac54c12deb694fe45 

### Vulnerability/Issue

Thread 'main' panicked in lucetc::decls::ModuleDecls::get_table

### Steps to reproduce the behavior 
- Download: [lucetc_panic_unwrap.zip](https://github.com/fastly/lucet/files/3391463/lucetc_panic_unwrap.zip)
- Run: `./target/release/lucetc lucetc_panic_unwrap.wasm`

#### Crash
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:373:21
```

#### Crash (RUST_BACKTRACE=1)
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:373:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::panicking::panic
             at src/libcore/panicking.rs:49
  11: lucetc::decls::ModuleDecls::get_table
  12: lucetc::table::write_table_data
  13: lucetc::compiler::Compiler::object_file
  14: lucetc::Lucetc::shared_object_file
  15: lucetc::main
  16: std::rt::lang_start::{{closure}}
  17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  18: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  20: std::panicking::try
             at src/libstd/panicking.rs:275
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  23: main
  24: __libc_start_main
  25: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

#### Crash (RUST_BACKTRACE=full)
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:373:21
stack backtrace:
   0:     0x5623e20fe8db - backtrace::backtrace::libunwind::trace::h9aefeba8a047a6fe
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1:     0x5623e20fe8db - backtrace::backtrace::trace_unsynchronized::hdf2f93b3a2c1de24
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2:     0x5623e20fe8db - std::sys_common::backtrace::_print::hd965b6bee154e2c5
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x5623e20fe8db - std::sys_common::backtrace::print::h1711ea6b4387aaa6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x5623e20fe8db - std::panicking::default_hook::{{closure}}::h0b61452e607a4bdf
                               at src/libstd/panicking.rs:200
   5:     0x5623e20fe5b7 - std::panicking::default_hook::h0a165fe2804b5780
                               at src/libstd/panicking.rs:214
   6:     0x5623e20ff050 - std::panicking::rust_panic_with_hook::ha3295d53a35861e3
                               at src/libstd/panicking.rs:477
   7:     0x5623e20febd2 - std::panicking::continue_panic_fmt::h66934f2d86c129ac
                               at src/libstd/panicking.rs:384
   8:     0x5623e20feab6 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x5623e212baad - core::panicking::panic_fmt::h16e27f3c0e00e289
                               at src/libcore/panicking.rs:85
  10:     0x5623e212b9ec - core::panicking::panic::h4ec09636afad5665
                               at src/libcore/panicking.rs:49
  11:     0x5623e1c36a0f - lucetc::decls::ModuleDecls::get_table::h8a11a811836487ad
  12:     0x5623e1c14435 - lucetc::table::write_table_data::h0aacdaf6b30ef5ba
  13:     0x5623e1c3181e - lucetc::compiler::Compiler::object_file::hd2b64637f4ae5538
  14:     0x5623e1b1df27 - lucetc::Lucetc::shared_object_file::he485a969b90d920f
  15:     0x5623e1b0fdd8 - lucetc::main::h7b276514f39cbe87
  16:     0x5623e1b236e3 - std::rt::lang_start::{{closure}}::h20df7461734dbd8d
  17:     0x5623e20fea53 - std::rt::lang_start_internal::{{closure}}::ha6cdc0674c227baf
                               at src/libstd/rt.rs:49
  18:     0x5623e20fea53 - std::panicking::try::do_call::hcfcd808f74618614
                               at src/libstd/panicking.rs:296
  19:     0x5623e210fb5a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:82
  20:     0x5623e20ff61d - std::panicking::try::h28299215a9cbdc2e
                               at src/libstd/panicking.rs:275
  21:     0x5623e20ff61d - std::panic::catch_unwind::h6d2adbec69dbd2ec
                               at src/libstd/panic.rs:394
  22:     0x5623e20ff61d - std::rt::lang_start_internal::ha819bd148e81f2bd
                               at src/libstd/rt.rs:48
  23:     0x5623e1b102c2 - main
  24:     0x7f693a166b97 - __libc_start_main
  25:     0x5623e1b0c63a - _start
  26:                0x0 - <unknown>
```

#### Feedback

I think this is due to the unwrap() line 439 inside lucetc/src/decls.rs

### PR DESCRIPTION
**Pull request by jedisct1**
Fixes #250

### CODE REVIEW

File: lucetc/src/decls.rs [hunk 1]
```diff
@@ -444,7 +444,12 @@ impl<'a> ModuleDecls<'a> {
             .ok_or_else(|| format_err!("table index out of bounds: {:?}", table_index))?;
         let exportable_tbl = self.info.tables.get(table_index).unwrap();
         let import_name = self.info.imported_tables.get(table_index);
-        let elems = self.info.table_elems.get(&table_index).unwrap().as_slice();
+        let elems = self
+            .info
+            .table_elems
+            .get(&table_index)
+            .ok_or_else(|| format_err!("table is not local: {:?}", table_index))?
```
Comment (awortman-fastly) [inline lucetc/src/decls.rs]: Could you `.context(LucetcErrorKind::Unsupported)` this error, please :D

Comment (jedisct1) [reply lucetc/src/decls.rs]: Sure. Done.
